name: deploy
on:
  pull_request:
    branches: [develop]
    types: [closed]

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    name: synchronization between local and remote repository
    runs-on: ubuntu-latest
    # 경고 무시
    env:
      CI: false
    # Nodejs 런타임 정보 설정 test
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: executing remote ssh commands with ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }} # ssh 접속용 ip
          username: ${{ secrets.USERNAME }} # root
          key: ${{ secrets.KEY }} # ssh 접속용 password
          port: ${{ secrets.PORT }} # ssh 접속용 port
          script: |
            cd /schooloud_front-end
            git checkout develop
            git pull origin develop
            cd /schooloud_front-end
            npm install
            npm run build
            sudo systemctl restart nginx
